audio:
  audio_path: data/raw/27042026.m4a
  overwrite_transcriptions: false
  transcriptions_path: data/processed/27042026v4-whisper-turbo3.txt
dataset: null
experiment_name: base_model_transcription
logger:
  formatter: '%(asctime)s [%(levelname)s] (%(name)s) %(message)s'
  log_file: logs/audio_transcription.log
  log_level: INFO
model:
  kernel: linear
  type: svm
project_name: AudioTranscriptor
text_processing:
  embedder: sentence_transformers
  lemmatization: true
  lowercase: true
  normalization_method: NFKD
  normalize_text: true
  remove_accents: true
  remove_fillers: true
  remove_special: true
  remove_stopwords: true
  spacy:
    model_name: pt_core_news_md
  stemmer_type: snowball
  stemming: true
  tokenizer: nltk
  tokenizer_language: portuguese
  vector_store: faiss
vectorization:
  max_features: 5000
  method: bow
  ngram_range:
  - 1
  - 2
whisper:
  model: turbo
